##############################################################################
# Multi-project makefile rules
#

all:
	@echo === Building for STM32H743-Nucleo144 ===============================
	@make --no-print-directory -f ./make/stm32h743_nucleo144.make all
	@echo ====================================================================

clean:
	-@make --no-print-directory -f ./make/stm32h743_nucleo144.make clean

#
##############################################################################
