##############################################################################
# Multi-project makefile rules
#

all:
	@echo === Building for ArduPilot_H743 ===============================
	@make --no-print-directory -f ./make/ArduPilot_H743.make all
	@echo ====================================================================

clean:
	-@make --no-print-directory -f ./make/ArduPilot_H743.make clean

#
##############################################################################
